# Generated by Django 5.1 on 2026-08-19 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(blank=True, help_text='e.g. $90,000 - $110,000', max_length=100)),
                ('job_url', models.URLField(blank=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='wishlist', max_length=20)),
                ('category', models.CharField(blank=True, help_text='e.g. Frontend, Backend, Data Science, Design', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True, help_text='Newline-separated list')),
                ('required_experience', models.TextField(blank=True)),
                ('key_technologies', models.TextField(blank=True, help_text='Newline-separated list')),
                ('interview_prep_suggestions', models.TextField(blank=True, help_text='Newline-separated list')),
                ('match_notes', models.TextField(blank=True, help_text='Optional AI job-match commentary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='tracker.application')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('video', 'Video Call'), ('onsite', 'Onsite'), ('technical', 'Technical'), ('hr', 'HR Round'), ('other', 'Other')], default='video', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tracker.application')),
            ],
            options={
                'ordering': ['interview_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='applications', to='tracker.tag'),
        ),
    ]
