# Generated by Django 5.1 on 2026-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='interview_questions',
            field=models.TextField(blank=True, help_text='Newline-separated list of likely interview questions'),
        ),
    ]
